### ISSUE TITLE
Unstable Training? White imges as result.

### ISSUE THREAD

**Issue by Alpe6825** [zhengyuf/IMavatar#3]
Hello, 

first of all thx for sharing the code. Very interesting work.

I tried to train IMavatar with your dataset, but after epoch 75 the results got worse again. 

This is epoch 95 for example:
![epoch_95_1](https://user-images.githubusercontent.com/51789043/174264998-418f6c90-d3d6-43f5-a43d-d1ba670672f8.png)

The only thing i noticed until now is that at least one sample in the dataset seems to be corrupt so that the training stops, but I simply continue training. 

After epoch 95 the results get a bit better but than white again. I know epoch 95 is quite far away from 1000, but do you think the training gets back to good results?  Maybe you have experience with that. 

I would be glad for any help.

**Comment by zhengyuf** [comment]
Hey,

I'm not so sure why this happens, but let's try to figure it out - 

White images usually mean that there is no geometry anymore. I did experience instability in training, but usually a smoothening in the geometry, or wrong LBS weight at the mouth, rather than complete disappearance of the head.

Could you explain what you mean by corrupted samples in the dataset?

**Comment by zhengyuf** [comment]
Also, which kind of GPU do you use?

**Comment by Alpe6825** [comment]
Corrupted samples was just a first wrong guess from me. I think the problem seem to be caused by something different. Sometimes the training breaks when computing the mask_loss in loss.py line 64.

![Screenshot from 2022-06-17 12-54-31](https://user-images.githubusercontent.com/51789043/174286738-70318c98-00bd-4c1d-b65e-9a299c319d31.png)
![Screenshot from 2022-06-17 12-53-39](https://user-images.githubusercontent.com/51789043/174286748-d08d6c7a-f9f8-428f-8c72-77d2de97b204.png)

It occurs when applying squeeze() to a tensor of size (1, 1).


> Also, which kind of GPU do you use?

I use a RTX 3090.

**Comment by zhengyuf** [comment]
Hey,

RTX 30xx seems to have problems with broyden's method used in IMavatar and the previous work SNARF. See [Here](https://github.com/xuchen-ethz/snarf/issues/3#issue-1096847424). I used RTX 2080Ti, but other GPUs (not RTX 30xx) should also work. 

PS: don't waste your time with A100, it doesn't work.

As for the error, it's because sdf_pred is usually shaped as [num_samples, 1] and sdf_pred.squeeze() will shape it to [num_samples]. But in this step, the num_samples is 1, and the squeeze() squeezed both dimensions. I did not notice this bug because this is normally a rare case, thank you for pointing this out, I'll correct this.

**Comment by Alpe6825** [comment]
I have now also organized a 2080Ti and it seems to work. :D 

Thanks a lot for this tip. I would probably never have thought of testing another GPU.

**Comment by lingtengqiu** [comment]
> Hey,
> 
> RTX 30xx seems to have problems with broyden's method used in IMavatar and the previous work SNARF. See [Here](https://github.com/xuchen-ethz/snarf/issues/3#issue-1096847424). I used RTX 2080Ti, but other GPUs (not RTX 30xx) should also work.
> 
> PS: don't waste your time with A100, it doesn't work.
> 
> As for the error, it's because sdf_pred is usually shaped as [num_samples, 1] and sdf_pred.squeeze() will shape it to [num_samples]. But in this step, the num_samples is 1, and the squeeze() squeezed both dimensions. I did not notice this bug because this is normally a rare case, thank you for pointing this out, I'll correct this.

Do you mean that the broyden method also not works well on A-100 like RTX3090?

**Comment by zhengyuf** [comment]
No, the last time I tried, it doesn't work on A 100 or RTX 3090.
