### ISSUE TITLE
camera matrices

### ISSUE THREAD

**Issue by UestcJay** [zhengyuf/IMavatar#4]
many thanks for your great work!  I have question about [this line code](https://github.com/zhengyuf/IMavatar/blob/74879455a0d604380d8865f506abc64f41d8c34e/code/utils/rend_util.py#L128), why should x -1?

**Comment by zhengyuf** [comment]
Hi,

It's just one way of implementation that works. In [the preprocessing code](https://github.com/zhengyuf/IMavatar/blob/74879455a0d604380d8865f506abc64f41d8c34e/preprocess/DECA/optimize.py#L32), it's done in the same way, which is why it currently works. 
But you can also remove both of the minus signs, but that might require a different initialization of camera location and direction. 

Best,
Yufeng

**Comment by UestcJay** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你的来件我已收到，谢谢。

**Comment by UestcJay** [comment]
> Hi,
> 
> It's just one way of implementation that works. In [the preprocessing code](https://github.com/zhengyuf/IMavatar/blob/74879455a0d604380d8865f506abc64f41d8c34e/preprocess/DECA/optimize.py#L32), it's done in the same way, which is why it currently works. But you can also remove both of the minus signs, but that might require a different initialization of camera location and direction.
> 
> Best, Yufeng

Thanks for your reply! Is the coordinate system follow the OpenCV convention[right, down, forward]?
