### ISSUE TITLE
How to create training datasets

### ISSUE THREAD

**Issue by Bai426** [zhengyuf/IMavatar#8]
Hi, Yufeng, I am wondering how to create my own datasets through cameras: 1) the image size is 512x512, 2) what is the camera speed or fps? 3) is there any special requirement like the face should be in the middle of images? or the background must be a single color? How about the lightness? 

Best,
Mike

**Comment by zhengyuf** [comment]
1) Image resolution can be arbitrary, we crop and resize the videos.
2) fps can also be arbitrary, we have an fps parameter in the preprocessing code.
3) Face should ideally be in the middle of the image, but if not, you can adjust it with cropping. However, then you must also adjust the camera intrinsic parameters. 
4) We used opencv to calibrate our cameras, with checkerboard images.
5) Environment lighting should be bright so that your shutters peed can be low, in order to avoid motion blur. Directional light works the best.

**Comment by Bai426** [comment]
Okay, these are very helpful. Thank you!
